//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWorkplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public short Row { get; set; }
        public short Place { get; set; }
        public string Client { get; set; }
        public int SessionId { get; set; }
        public int OrderID { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
